# Generated by Django 3.1.1 on 2020-10-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='comment',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
