# Generated by Django 3.1.1 on 2020-10-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0003_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature',
            field=models.TextField(max_length=30),
        ),
    ]
