# Generated by Django 3.1.1 on 2020-10-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travell', '0004_auto_20201017_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.ManyToManyField(to='travell.Features'),
        ),
    ]
